package com.tarsil.distribution.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF001452)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001452)
val md_theme_light_secondary = Color(0xFF4359A9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF001452) // For primary action buttons
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFF3F4357)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE3E2E6)
val md_theme_light_onTertiaryContainer = Color(0xFF1B1B1F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFF3F4F9)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFFE1E2EC)
val md_theme_light_inverseOnSurface = Color(0xFFF3F4F9)
val md_theme_light_inverseSurface = Color(0xFF1B1B1F)
val md_theme_light_inversePrimary = Color(0xFFB1C5FF)
val md_theme_light_surfaceTint = Color(0xFF001452)
val md_theme_light_outlineVariant = Color(0xFFE1E2EC)
val md_theme_light_scrim = Color(0xFF000000)
